import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react"
import  RecommendationsProviders  from "../context/RecommendationsProvider";

import "../styles/globals.css";
import { SpotifySession } from "@/types/types";
import PlaylistProvider from "@/context/PlaylsitsProvider";

export const metadata: Metadata = {
  title: { default: "Dashboard", template: "%s | My Website" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode,
  session: SpotifySession,
}) {
  return (
    <html
      className="dark"
      lang="en"
      suppressHydrationWarning
    >
      <head></head>
      <body className="dark text-foreground">
        <SessionProvider session={session}>
          <RecommendationsProviders>
            <PlaylistProvider>
              {children}
            </PlaylistProvider>
            </RecommendationsProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
