import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "../styles/globals.css";
import { Theme } from "@radix-ui/themes";

// import "../styles/globals.css";
import GlobalHeader from "./components/GlobalHeader/GlobalHeader";
import ThemeProvider from "context/ThemeProvider";
import RecommendationsProvider from "context/RecommendationsProvider";

export const metadata: Metadata = {
  title: { default: "Dashboard", template: "%s | My Website" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <head></head>
      <ThemeProvider>
        <RecommendationsProvider>
          <body>
            <Theme
              id="application-root"
              accentColor="indigo"
              grayColor="slate"
              appearance="dark"
              panelBackground="translucent"
              scaling="100%"
              radius="large"
            >
              {children}
            </Theme>
          </body>
        </RecommendationsProvider>
      </ThemeProvider>
    </html>
  );
}
