// import Header from "./header"
// import Footer from "./footer"
import { Box, Grid } from '@mui/material';
import Head from 'next/head';
import TopBar from './bars/top/TopBar';
// import styles from '@/styles/components/AppLayout.module.css';

export default function Layout(props) {
  return (
    <>
      <Head>
        <title>In Search of Mood: A Spotify® App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopBar />
        <Grid container>
          <Grid item xs={12} md={7}>
            <Box mt={2} px={2}>
              {props.children}
            </Box>
          </Grid>
          <Grid item xs={12} md={3}>
            <h2>add to group</h2>
          </Grid>
          <Grid item xs={12} md={2}>
            <h2>add group to playlist</h2>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
