import { VercelToolbar } from '@vercel/toolbar/next';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'In search of mood - Spotify Playlist suggestion and management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const shouldInjectToolbar = process.env.NODE_ENV === 'development';
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <VercelToolbar />

      </body>
    </html>
  )
}
